<?php
declare(strict_types=1);

namespace Plaisio\Config\Test;

use Plaisio\C;
use Plaisio\CompanyResolver\UniCompanyResolver;
use Plaisio\Config\CoreConfig;
use Plaisio\Kernel\Nub;
use SetBased\Stratum\MySql\MySqlDefaultConnector;

/**
 * Kernel for testing purposes.
 */
class TestKernel extends Nub
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Object constructor.
   */
  public function __construct()
  {
    parent::__construct();
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the data layer generated by PhpStratum.
   *
   * @return Object
   */
  protected function getDL(): Object
  {
    $connector = new MySqlDefaultConnector('localhost', 'test', 'test', 'test');

    return new TestDataLayer($connector);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for deriving the company.
   *
   * @return UniCompanyResolver
   */
  protected function getCompanyResolver(): UniCompanyResolver
  {
    return new UniCompanyResolver(C::CMP_ID_SYSTEM);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns helper object for configuration parameters.
   *
   * @return CoreConfig
   */
  protected function getConfig(): CoreConfig
  {
    return new CoreConfig();
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
